cmake_minimum_required(VERSION 3.5)
project(ep_gazebo_control)
find_package(ament_cmake REQUIRED)
find_package(gazebo REQUIRED)
find_package(gazebo_ros2_control REQUIRED)
find_package(hardware_interface REQUIRED)
find_package(rclcpp REQUIRED)
find_package(pluginlib REQUIRED)
add_library(ep_position_servo SHARED src/position_servo.cpp)
target_compile_features(ep_position_servo PUBLIC cxx_std_14)
target_compile_options(ep_position_servo PRIVATE -Wall -Wextra)
target_include_directories(ep_position_servo PRIVATE ${GAZEBO_INCLUDE_DIRS})
target_link_libraries(ep_position_servo ${GAZEBO_LIBRARIES})
ament_target_dependencies(ep_position_servo gazebo_ros2_control hardware_interface rclcpp pluginlib)
pluginlib_export_plugin_description_file(gazebo_ros2_control plugins.xml)
install(TARGETS ep_position_servo LIBRARY DESTINATION lib)
ament_package()
