# 规划限速：旋转关节使用 rad/s、rad/s²，夹爪移动关节使用 m/s、m/s²。
joint_limits:
  arm_1_joint:
    has_velocity_limits: true
    max_velocity: 0.35
    has_acceleration_limits: true
    max_acceleration: 0.5
  arm_2_joint:
    has_velocity_limits: true
    max_velocity: 0.35
    has_acceleration_limits: true
    max_acceleration: 0.5
  left_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.025
    has_acceleration_limits: true
    max_acceleration: 0.05
